name: Berlin_Wolff_Park

services:
  berlin_wolff_park_db:
    image: postgres:14-alpine3.17
    container_name: berlin-wolff-park-db
    volumes:
      - db_berlin_wolff_park:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park:
    image: hub-manager-service:latest
    container_name: berlin-wolff-park-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_wolff_park_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Wolff_Park
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-wolff-park-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-wolff-park-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Wolff_Park.rule=PathPrefix(`/api/Berlin_Wolff_Park`)"
      - "traefik.http.routers.Berlin_Wolff_Park.entrypoints=web"
      - "traefik.http.services.Berlin_Wolff_Park.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Wolff_Park-replace.replacepathregex.regex=^/api/Berlin_Wolff_Park(.*)"
      - "traefik.http.middlewares.Berlin_Wolff_Park-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Wolff_Park.middlewares=Berlin_Wolff_Park-replace"
    networks:
      - hub_network

  berlin_wolff_park_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-wolff-park-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_wolff_park.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_wolff_park_col1:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col2:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col3:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col4:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col5:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col6:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col7:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col8:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col9:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col10:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col11:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col12:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col13:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col14:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col15:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col15
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col15
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col16:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col16
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col16
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col17:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col17
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col17
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col18:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col18
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col18
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col19:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col19
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col19
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col20:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col20
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col20
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col21:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col21
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col21
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col22:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col22
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col22
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col23:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col23
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col23
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col24:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col24
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col24
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col25:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col25
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col25
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col26:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col26
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col26
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col27:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col27
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col27
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col28:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col28
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col28
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col29:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col29
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col29
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col30:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col30
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col30
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col31:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col31
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col31
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col32:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col32
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col32
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col33:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col33
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col33
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col34:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col34
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col34
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col35:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col35
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col35
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col36:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col36
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col36
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_wolff_park_col37:
    image: charger-manager-service:latest
    container_name: berlin-wolff-park-col37
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Wolff_Park
      CHARGER_TO_HANDLE: Berlin_Wolff_Park_col37
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_wolff_park:

networks:
  hub_network:
    driver: bridge