name: Berlin_Savignyplatz

services:
  berlin_savignyplatz_db:
    image: postgres:14-alpine3.17
    container_name: berlin-savignyplatz-db
    volumes:
      - db_berlin_savignyplatz:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz:
    image: hub-manager-service:latest
    container_name: berlin-savignyplatz-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_savignyplatz_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Savignyplatz
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-savignyplatz-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-savignyplatz-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Savignyplatz.rule=PathPrefix(`/api/Berlin_Savignyplatz`)"
      - "traefik.http.routers.Berlin_Savignyplatz.entrypoints=web"
      - "traefik.http.services.Berlin_Savignyplatz.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Savignyplatz-replace.replacepathregex.regex=^/api/Berlin_Savignyplatz(.*)"
      - "traefik.http.middlewares.Berlin_Savignyplatz-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Savignyplatz.middlewares=Berlin_Savignyplatz-replace"
    networks:
      - hub_network

  berlin_savignyplatz_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-savignyplatz-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_savignyplatz.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_savignyplatz_col1:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col2:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col3:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col4:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col5:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col6:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col7:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col8:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col9:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col10:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_savignyplatz_col11:
    image: charger-manager-service:latest
    container_name: berlin-savignyplatz-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Savignyplatz
      CHARGER_TO_HANDLE: Berlin_Savignyplatz_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_savignyplatz:

networks:
  hub_network:
    driver: bridge