name: Berlin_Spichernstr

services:
  berlin_spichernstr_db:
    image: postgres:14-alpine3.17
    container_name: berlin-spichernstr-db
    volumes:
      - db_berlin_spichernstr:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr:
    image: hub-manager-service:latest
    container_name: berlin-spichernstr-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_spichernstr_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Spichernstr
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-spichernstr-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-spichernstr-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Spichernstr.rule=PathPrefix(`/api/Berlin_Spichernstr`)"
      - "traefik.http.routers.Berlin_Spichernstr.entrypoints=web"
      - "traefik.http.services.Berlin_Spichernstr.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Spichernstr-replace.replacepathregex.regex=^/api/Berlin_Spichernstr(.*)"
      - "traefik.http.middlewares.Berlin_Spichernstr-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Spichernstr.middlewares=Berlin_Spichernstr-replace"
    networks:
      - hub_network

  berlin_spichernstr_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-spichernstr-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_spichernstr.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_spichernstr_col1:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col2:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col3:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col4:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col5:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col6:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col7:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col8:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col9:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col10:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col11:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col12:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_spichernstr_col13:
    image: charger-manager-service:latest
    container_name: berlin-spichernstr-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Spichernstr
      CHARGER_TO_HANDLE: Berlin_Spichernstr_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_spichernstr:

networks:
  hub_network:
    driver: bridge