name: Berlin_Remise

services:
  berlin_remise_db:
    image: postgres:14-alpine3.17
    container_name: berlin-remise-db
    volumes:
      - db_berlin_remise:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise:
    image: hub-manager-service:latest
    container_name: berlin-remise-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_remise_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Remise
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-remise-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-remise-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Remise.rule=PathPrefix(`/api/Berlin_Remise`)"
      - "traefik.http.routers.Berlin_Remise.entrypoints=web"
      - "traefik.http.services.Berlin_Remise.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Remise-replace.replacepathregex.regex=^/api/Berlin_Remise(.*)"
      - "traefik.http.middlewares.Berlin_Remise-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Remise.middlewares=Berlin_Remise-replace"
    networks:
      - hub_network

  berlin_remise_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-remise-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_remise.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_remise_col1:
    image: charger-manager-service:latest
    container_name: berlin-remise-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col2:
    image: charger-manager-service:latest
    container_name: berlin-remise-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col3:
    image: charger-manager-service:latest
    container_name: berlin-remise-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col4:
    image: charger-manager-service:latest
    container_name: berlin-remise-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col5:
    image: charger-manager-service:latest
    container_name: berlin-remise-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col6:
    image: charger-manager-service:latest
    container_name: berlin-remise-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col7:
    image: charger-manager-service:latest
    container_name: berlin-remise-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col8:
    image: charger-manager-service:latest
    container_name: berlin-remise-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col9:
    image: charger-manager-service:latest
    container_name: berlin-remise-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col10:
    image: charger-manager-service:latest
    container_name: berlin-remise-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col11:
    image: charger-manager-service:latest
    container_name: berlin-remise-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col12:
    image: charger-manager-service:latest
    container_name: berlin-remise-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_remise_col13:
    image: charger-manager-service:latest
    container_name: berlin-remise-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Remise
      CHARGER_TO_HANDLE: Berlin_Remise_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_remise:

networks:
  hub_network:
    driver: bridge