name: hub_potsdamer_platz

services:
  potsdamer_platz_db:
    image: postgres:14-alpine3.17
    container_name: hub-db-potsdamer-platz
    volumes:
      - db_potsdamer_platz:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  potsdamer_platz:
    image: hub-manager-service:latest
    container_name: potsdamer-platz
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      potsdamer_platz_db:
        condition: service_healthy
    environment:
      HUB_TO_HANDLE: hub_potsdamer_platz
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://charger-gateway-potsdamer-platz:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://hub-db-potsdamer-platz:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hub-potsdamer-platz.rule=PathPrefix(`/api/hub_potsdamer_platz`)"
      - "traefik.http.routers.hub-potsdamer-platz.entrypoints=web"
      - "traefik.http.services.hub-potsdamer-platz.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.hub-potsdamer-platz-replace.replacepathregex.regex=^/api/hub_potsdamer_platz(.*)"
      - "traefik.http.middlewares.hub-potsdamer-platz-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.hub-potsdamer-platz.middlewares=hub-potsdamer-platz-replace"
    networks:
      - hub_network

  charger_gateway_potsdamer_platz:
    image: charger-gateway:latest
    container_name: charger-gateway-potsdamer-platz
    expose:
      - "9000"
    volumes:
      - ./additional_config/potsdamer_platz.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  potsdamer_platz_col1:
    image: charger-manager-service:latest
    container_name: potsdamer-platz-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: hub_potsdamer_platz
      CHARGER_TO_HANDLE: hub_potsdamer_platz_col1

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  potsdamer_platz_col2:
    image: charger-manager-service:latest
    container_name: potsdamer-platz-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: hub_potsdamer_platz
      CHARGER_TO_HANDLE: hub_potsdamer_platz_col2

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_potsdamer_platz:

networks:
  hub_network:
    driver: bridge