name: Berlin_Tempelhof

services:
  berlin_tempelhof_db:
    image: postgres:14-alpine3.17
    container_name: berlin-tempelhof-db
    volumes:
      - db_berlin_tempelhof:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof:
    image: hub-manager-service:latest
    container_name: berlin-tempelhof-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_tempelhof_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Tempelhof
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-tempelhof-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-tempelhof-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Tempelhof.rule=PathPrefix(`/api/Berlin_Tempelhof`)"
      - "traefik.http.routers.Berlin_Tempelhof.entrypoints=web"
      - "traefik.http.services.Berlin_Tempelhof.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Tempelhof-replace.replacepathregex.regex=^/api/Berlin_Tempelhof(.*)"
      - "traefik.http.middlewares.Berlin_Tempelhof-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Tempelhof.middlewares=Berlin_Tempelhof-replace"
    networks:
      - hub_network

  berlin_tempelhof_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-tempelhof-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_tempelhof.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_tempelhof_col1:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col2:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col3:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col4:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col5:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col6:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col7:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col8:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col9:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col10:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col11:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col12:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col13:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col14:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col15:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col15
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col15
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col16:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col16
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col16
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col17:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col17
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col17
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col18:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col18
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col18
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col19:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col19
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col19
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col20:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col20
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col20
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col21:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col21
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col21
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col22:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col22
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col22
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col23:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col23
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col23
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col24:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col24
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col24
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col25:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col25
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col25
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col26:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col26
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col26
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col27:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col27
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col27
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col28:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col28
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col28
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_tempelhof_col29:
    image: charger-manager-service:latest
    container_name: berlin-tempelhof-col29
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Tempelhof_col29
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_tempelhof:

networks:
  hub_network:
    driver: bridge