name: Berlin_Memhardstr

services:
  berlin_memhardstr_db:
    image: postgres:14-alpine3.17
    container_name: berlin-memhardstr-db
    volumes:
      - db_berlin_memhardstr:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr:
    image: hub-manager-service:latest
    container_name: berlin-memhardstr-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_memhardstr_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Memhardstr
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-memhardstr-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-memhardstr-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Memhardstr.rule=PathPrefix(`/api/Berlin_Memhardstr`)"
      - "traefik.http.routers.Berlin_Memhardstr.entrypoints=web"
      - "traefik.http.services.Berlin_Memhardstr.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Memhardstr-replace.replacepathregex.regex=^/api/Berlin_Memhardstr(.*)"
      - "traefik.http.middlewares.Berlin_Memhardstr-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Memhardstr.middlewares=Berlin_Memhardstr-replace"
    networks:
      - hub_network

  berlin_memhardstr_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-memhardstr-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_memhardstr.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_memhardstr_col1:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col2:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col3:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col4:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col5:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col6:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col7:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col8:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col9:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col10:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col11:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col12:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col13:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col14:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col15:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col15
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col15
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col16:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col16
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col16
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col17:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col17
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col17
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col18:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col18
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col18
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col19:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col19
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col19
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col20:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col20
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col20
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col21:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col21
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col21
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col22:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col22
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col22
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col23:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col23
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col23
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col24:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col24
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col24
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col25:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col25
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col25
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col26:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col26
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col26
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col27:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col27
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col27
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col28:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col28
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col28
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col29:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col29
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col29
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col30:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col30
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col30
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col31:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col31
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col31
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col32:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col32
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col32
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col33:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col33
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col33
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col34:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col34
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col34
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_memhardstr_col35:
    image: charger-manager-service:latest
    container_name: berlin-memhardstr-col35
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Memhardstr
      CHARGER_TO_HANDLE: Berlin_Memhardstr_col35
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_memhardstr:

networks:
  hub_network:
    driver: bridge