name: Berlin_Linden

services:
  berlin_linden_db:
    image: postgres:14-alpine3.17
    container_name: berlin-linden-db
    volumes:
      - db_berlin_linden:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden:
    image: hub-manager-service:latest
    container_name: berlin-linden-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_linden_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Linden
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-linden-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-linden-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Linden.rule=PathPrefix(`/api/Berlin_Linden`)"
      - "traefik.http.routers.Berlin_Linden.entrypoints=web"
      - "traefik.http.services.Berlin_Linden.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Linden-replace.replacepathregex.regex=^/api/Berlin_Linden(.*)"
      - "traefik.http.middlewares.Berlin_Linden-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Linden.middlewares=Berlin_Linden-replace"
    networks:
      - hub_network

  berlin_linden_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-linden-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_linden.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_linden_col1:
    image: charger-manager-service:latest
    container_name: berlin-linden-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col2:
    image: charger-manager-service:latest
    container_name: berlin-linden-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col3:
    image: charger-manager-service:latest
    container_name: berlin-linden-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col4:
    image: charger-manager-service:latest
    container_name: berlin-linden-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col5:
    image: charger-manager-service:latest
    container_name: berlin-linden-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col6:
    image: charger-manager-service:latest
    container_name: berlin-linden-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col7:
    image: charger-manager-service:latest
    container_name: berlin-linden-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col8:
    image: charger-manager-service:latest
    container_name: berlin-linden-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col9:
    image: charger-manager-service:latest
    container_name: berlin-linden-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col10:
    image: charger-manager-service:latest
    container_name: berlin-linden-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col11:
    image: charger-manager-service:latest
    container_name: berlin-linden-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col12:
    image: charger-manager-service:latest
    container_name: berlin-linden-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col13:
    image: charger-manager-service:latest
    container_name: berlin-linden-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col14:
    image: charger-manager-service:latest
    container_name: berlin-linden-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col15:
    image: charger-manager-service:latest
    container_name: berlin-linden-col15
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col15
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col16:
    image: charger-manager-service:latest
    container_name: berlin-linden-col16
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col16
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col17:
    image: charger-manager-service:latest
    container_name: berlin-linden-col17
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col17
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col18:
    image: charger-manager-service:latest
    container_name: berlin-linden-col18
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col18
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col19:
    image: charger-manager-service:latest
    container_name: berlin-linden-col19
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col19
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col20:
    image: charger-manager-service:latest
    container_name: berlin-linden-col20
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col20
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col21:
    image: charger-manager-service:latest
    container_name: berlin-linden-col21
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col21
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col22:
    image: charger-manager-service:latest
    container_name: berlin-linden-col22
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col22
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col23:
    image: charger-manager-service:latest
    container_name: berlin-linden-col23
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col23
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col24:
    image: charger-manager-service:latest
    container_name: berlin-linden-col24
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col24
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col25:
    image: charger-manager-service:latest
    container_name: berlin-linden-col25
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col25
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col26:
    image: charger-manager-service:latest
    container_name: berlin-linden-col26
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col26
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col27:
    image: charger-manager-service:latest
    container_name: berlin-linden-col27
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col27
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col28:
    image: charger-manager-service:latest
    container_name: berlin-linden-col28
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col28
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col29:
    image: charger-manager-service:latest
    container_name: berlin-linden-col29
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col29
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col30:
    image: charger-manager-service:latest
    container_name: berlin-linden-col30
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col30
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col31:
    image: charger-manager-service:latest
    container_name: berlin-linden-col31
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col31
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col32:
    image: charger-manager-service:latest
    container_name: berlin-linden-col32
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col32
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col33:
    image: charger-manager-service:latest
    container_name: berlin-linden-col33
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col33
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col34:
    image: charger-manager-service:latest
    container_name: berlin-linden-col34
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col34
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col35:
    image: charger-manager-service:latest
    container_name: berlin-linden-col35
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col35
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col36:
    image: charger-manager-service:latest
    container_name: berlin-linden-col36
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col36
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col37:
    image: charger-manager-service:latest
    container_name: berlin-linden-col37
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col37
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col38:
    image: charger-manager-service:latest
    container_name: berlin-linden-col38
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col38
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col39:
    image: charger-manager-service:latest
    container_name: berlin-linden-col39
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col39
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_linden_col40:
    image: charger-manager-service:latest
    container_name: berlin-linden-col40
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Linden
      CHARGER_TO_HANDLE: Berlin_Linden_col40
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_linden:

networks:
  hub_network:
    driver: bridge