name: Berlin_Friedhof

services:
  berlin_friedhof_db:
    image: postgres:14-alpine3.17
    container_name: berlin-friedhof-db
    volumes:
      - db_berlin_friedhof:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof:
    image: hub-manager-service:latest
    container_name: berlin-friedhof-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_friedhof_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Friedhof
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-friedhof-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-friedhof-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Friedhof.rule=PathPrefix(`/api/Berlin_Friedhof`)"
      - "traefik.http.routers.Berlin_Friedhof.entrypoints=web"
      - "traefik.http.services.Berlin_Friedhof.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Friedhof-replace.replacepathregex.regex=^/api/Berlin_Friedhof(.*)"
      - "traefik.http.middlewares.Berlin_Friedhof-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Friedhof.middlewares=Berlin_Friedhof-replace"
    networks:
      - hub_network

  berlin_friedhof_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-friedhof-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_friedhof.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_friedhof_col1:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col2:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col3:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col4:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col5:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col6:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col7:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col8:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col9:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col10:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col11:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col12:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col13:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col14:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col15:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col15
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col15
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col16:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col16
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col16
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col17:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col17
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col17
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col18:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col18
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col18
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_friedhof_col19:
    image: charger-manager-service:latest
    container_name: berlin-friedhof-col19
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Friedhof
      CHARGER_TO_HANDLE: Berlin_Friedhof_col19
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_friedhof:

networks:
  hub_network:
    driver: bridge