name: Berlin_Neukölln

services:
  berlin_neukolln_db:
    image: postgres:14-alpine3.17
    container_name: berlin-neukolln-db
    volumes:
      - db_berlin_neukolln:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln:
    image: hub-manager-service:latest
    container_name: berlin-neukolln-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_neukolln_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Neukölln
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-neukolln-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-neukolln-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Neukölln.rule=PathPrefix(`/api/Berlin_Neukölln`)"
      - "traefik.http.routers.Berlin_Neukölln.entrypoints=web"
      - "traefik.http.services.Berlin_Neukölln.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Neukölln-replace.replacepathregex.regex=^/api/Berlin_Neukölln(.*)"
      - "traefik.http.middlewares.Berlin_Neukölln-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Neukölln.middlewares=Berlin_Neukölln-replace"
    networks:
      - hub_network

  berlin_neukolln_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-neukolln-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_neukolln.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_neukolln_col1:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col2:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col3:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col4:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col5:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col6:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col7:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col8:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col9:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col10:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col11:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col12:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col13:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col14:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col15:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col15
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col15
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col16:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col16
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col16
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_neukolln_col17:
    image: charger-manager-service:latest
    container_name: berlin-neukolln-col17
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Neukölln
      CHARGER_TO_HANDLE: Berlin_Neukölln_col17
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_neukolln:

networks:
  hub_network:
    driver: bridge