name: Berlin_Rehberge

services:
  berlin_rehberge_db:
    image: postgres:14-alpine3.17
    container_name: berlin-rehberge-db
    volumes:
      - db_berlin_rehberge:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge:
    image: hub-manager-service:latest
    container_name: berlin-rehberge-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_rehberge_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Rehberge
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-rehberge-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-rehberge-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Rehberge.rule=PathPrefix(`/api/Berlin_Rehberge`)"
      - "traefik.http.routers.Berlin_Rehberge.entrypoints=web"
      - "traefik.http.services.Berlin_Rehberge.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Rehberge-replace.replacepathregex.regex=^/api/Berlin_Rehberge(.*)"
      - "traefik.http.middlewares.Berlin_Rehberge-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Rehberge.middlewares=Berlin_Rehberge-replace"
    networks:
      - hub_network

  berlin_rehberge_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-rehberge-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_rehberge.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_rehberge_col1:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col2:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col3:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col4:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col5:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col6:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col7:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col8:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col9:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col10:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col11:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col12:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col13:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_rehberge_col14:
    image: charger-manager-service:latest
    container_name: berlin-rehberge-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Rehberge
      CHARGER_TO_HANDLE: Berlin_Rehberge_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_rehberge:

networks:
  hub_network:
    driver: bridge