name: Berlin_Hansaplatz

services:
  berlin_hansaplatz_db:
    image: postgres:14-alpine3.17
    container_name: berlin-hansaplatz-db
    volumes:
      - db_berlin_hansaplatz:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz:
    image: hub-manager-service:latest
    container_name: berlin-hansaplatz-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_hansaplatz_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Hansaplatz
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-hansaplatz-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-hansaplatz-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Hansaplatz.rule=PathPrefix(`/api/Berlin_Hansaplatz`)"
      - "traefik.http.routers.Berlin_Hansaplatz.entrypoints=web"
      - "traefik.http.services.Berlin_Hansaplatz.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Hansaplatz-replace.replacepathregex.regex=^/api/Berlin_Hansaplatz(.*)"
      - "traefik.http.middlewares.Berlin_Hansaplatz-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Hansaplatz.middlewares=Berlin_Hansaplatz-replace"
    networks:
      - hub_network

  berlin_hansaplatz_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-hansaplatz-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_hansaplatz.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_hansaplatz_col1:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col2:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col3:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col3
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col3
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col4:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col4
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col4
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col5:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col5
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col5
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col6:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col6
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col6
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col7:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col7
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col7
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col8:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col8
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col8
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col9:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col9
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col9
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col10:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col10
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col10
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col11:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col11
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col11
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col12:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col12
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col12
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col13:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col13
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col13
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col14:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col14
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col14
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col15:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col15
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col15
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col16:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col16
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col16
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col17:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col17
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col17
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col18:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col18
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col18
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col19:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col19
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col19
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col20:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col20
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col20
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

  berlin_hansaplatz_col21:
    image: charger-manager-service:latest
    container_name: berlin-hansaplatz-col21
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Hansaplatz
      CHARGER_TO_HANDLE: Berlin_Hansaplatz_col21
      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8090/ws/simulation
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_hansaplatz:

networks:
  hub_network:
    driver: bridge