name: Berlin_Alt_Tempelhof

services:
  berlin_alt_tempelhof_db:
    image: postgres:14-alpine3.17
    container_name: berlin-alt-tempelhof-db
    volumes:
      - db_berlin_alt_tempelhof:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hub_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - hub_network

  berlin_alt_tempelhof:
    image: hub-manager-service:latest
    container_name: berlin-alt-tempelhof-hub
    expose:
      - "8081"
    depends_on:
      traefik:
        condition: service_started
      berlin_alt_tempelhof_db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    environment:
      HUB_TO_HANDLE: Berlin_Alt_Tempelhof
      INITIALIZE_ON_STARTUP: true
      CHARGER_GATEWAY_URL: http://berlin-alt-tempelhof-charger-gateway:9000
      INITIAL_DELAY_POLL: 5000
      FIXED_DELAY_POLL: 5000

      KAFKA_SERVER: broker:29092
      KAFKA_TOPIC: hub_state

      SIMULATION_API_BASE_URL: http://host.docker.internal:8090/api

      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_URL: jdbc:postgresql://berlin-alt-tempelhof-db:5432/hub_db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.Berlin_Alt_Tempelhof.rule=PathPrefix(`/api/Berlin_Alt_Tempelhof`)"
      - "traefik.http.routers.Berlin_Alt_Tempelhof.entrypoints=web"
      - "traefik.http.services.Berlin_Alt_Tempelhof.loadbalancer.server.port=8081"

      - "traefik.http.middlewares.Berlin_Alt_Tempelhof-replace.replacepathregex.regex=^/api/Berlin_Alt_Tempelhof(.*)"
      - "traefik.http.middlewares.Berlin_Alt_Tempelhof-replace.replacepathregex.replacement=/api/hub$$1"
      - "traefik.http.routers.Berlin_Alt_Tempelhof.middlewares=Berlin_Alt_Tempelhof-replace"
    networks:
      - hub_network

  berlin_alt_tempelhof_charger_gateway:
    image: charger-gateway:latest
    container_name: berlin-alt-tempelhof-charger-gateway
    expose:
      - "9000"
    volumes:
      - ./gateway_config/berlin_alt_tempelhof.yml:/app/additional_config/application.yml
    networks:
      - hub_network

  berlin_alt_tempelhof_col1:
    image: charger-manager-service:latest
    container_name: berlin-alt-tempelhof-col1
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Alt_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Alt_Tempelhof_col1
      SIMULATION_API_BASE_URL: http://host.docker.internal:8070/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8070/ws/bot
    restart: unless-stopped
    networks:
      - hub_network

  berlin_alt_tempelhof_col2:
    image: charger-manager-service:latest
    container_name: berlin-alt-tempelhof-col2
    expose:
      - "8080"
    depends_on:
      traefik:
        condition: service_started
      init_service:
        condition: service_completed_successfully
    environment:
      INITIALIZE_ON_STARTUP: true
      HUB_TO_HANDLE: Berlin_Alt_Tempelhof
      CHARGER_TO_HANDLE: Berlin_Alt_Tempelhof_col2
      SIMULATION_API_BASE_URL: http://host.docker.internal:8070/api
      SIMULATION_WEBSOCKET_URL: ws://host.docker.internal:8070/ws/bot
    restart: unless-stopped
    networks:
      - hub_network

volumes:
  db_berlin_alt_tempelhof:

networks:
  hub_network:
    driver: bridge