server:
  port: 9000

spring:
  application:
    name: charger-gateway

resilience4j:
  circuitbreaker:
    instances:
      chargerManagerService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
