name: hub_zone

services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - hub_network

  init_service:
    image: curlimages/curl:latest
    container_name: init-service
    command: ["curl", "--fail", "-X", "POST", "http://host.docker.internal:8090/api/hub"]
    restart: "no"
    networks:
      - hub_network

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    expose:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - hub_network

  broker-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: broker-ui
    depends_on:
      broker:
        condition: service_started
    ports:
      - "9091:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    networks:
      - hub_network

include:
  - ./hub_zones/docker-compose.berlin_alt_tempelhof.yml
  # - ./hub_zones/docker-compose.berlin_danzinger.yml
  # - ./hub_zones/docker-compose.berlin_friedhof.yml
  # - ./hub_zones/docker-compose.berlin_hamburger.yml
  # - ./hub_zones/docker-compose.berlin_hansaplatz.yml
  # - ./hub_zones/docker-compose.berlin_heinrich_heine.yml
  # - ./hub_zones/docker-compose.berlin_hospital.yml
  # - ./hub_zones/docker-compose.berlin_humboldthain.yml
  # - ./hub_zones/docker-compose.berlin_innenstadt.yml
  # - ./hub_zones/docker-compose.berlin_linden.yml
  # - ./hub_zones/docker-compose.berlin_memhardstr.yml
  # - ./hub_zones/docker-compose.berlin_neukolln.yml
  # - ./hub_zones/docker-compose.berlin_potsdamer_platz.yml
  # - ./hub_zones/docker-compose.berlin_prenzlauer_berg.yml
  # - ./hub_zones/docker-compose.berlin_rehberge.yml
  # - ./hub_zones/docker-compose.berlin_remise.yml
  # - ./hub_zones/docker-compose.berlin_rosenthaler.yml
  # - ./hub_zones/docker-compose.berlin_savignyplatz.yml
  # - ./hub_zones/docker-compose.berlin_schoneberg.yml
  # - ./hub_zones/docker-compose.berlin_sophienkirchhof.yml
  # - ./hub_zones/docker-compose.berlin_spichernstr.yml
  # - ./hub_zones/docker-compose.berlin_tempelhof.yml
  # - ./hub_zones/docker-compose.berlin_wolff_park.yml


networks:
  hub_network:
    driver: bridge